export const projectList = [
  {
    id: 1,
    title: "KitchenTools",
    projectUrl: "kitchentools",
    bgImg: "KitchenTools.jpg",
    desc: "<p>Basic webshop with cart function. Under development.</p><ul><li>responsive</li><li>SEO friendly url</li></ul>",
    technologies: ["React", "Express", "MongoDB", "Node"],
  },
  {
    id: 2,
    title: "HealthyLife",
    projectUrl: "helife",
    bgImg: "helife.jpg",
    desc: "<p>This website was created as part of an international project. In parallel, several similar websites with a different focus were created for the clients.</p><ul><li>multilingual website (6 languages)</li><li>responsive, parallax</li><li>fullscreen background slideshow</li><li>Google Fonts</li><li>possibility to send a message</li></ul>",
    technologies: ["React", "Bootstrap", "PHP"],
  },
  {
    id: 18,
    title: "we love healthy",
    projectUrl: "wlh",
    bgImg: "wlh.jpg",
    desc: "<p>This website is connected to the HealthyLife project.</p><p><ul><li>bilingual</li><li>responsive, parallax</li><li>contact form</li></ul></p>",
    technologies: ["React", "Bootstrap", "PHP"],
  },
  {
    id: 3,
    title: "Viragoutlet",
    projectUrl: "viragoutlet",
    bgImg: "viragoutlet.jpg",
    desc: "<p>This is a flower wholesale webshop with user-friendly administration panel and online payment option.</p><p><ul><li>bilingual</li><li>responsive</li></ul></p>",
    technologies: [
      "HTML",
      "CSS",
      "Bootstrap",
      "JavaScript/jQuery",
      "PHP",
      "MySQL",
    ],
  },
  {
    id: 4,
    title: "Tuningkereskedes",
    projectUrl: "tuningkereskedes",
    bgImg: "tuningkereskedes.jpg",
    desc: "<p>Responsive website with user-friendly administration panel. The website also contains a webshop function, which was temporarily deactivated at the customer's request.</p><br /><ul><li>responsive</li><li>SEO</li><li>products</li><li>references</li><li>forum</li><li>news</li><li>User's car</li><li>Contact form</li></ul>",
    technologies: ["HTML", "CSS", "Bootstrap", "JavaScript", "PHP", "MySQL"],
  },
  {
    id: 6,
    title: "Adrazeta",
    projectUrl: "adrazeta",
    bgImg: "adrazeta.jpg",
    desc: "<p>This website connects to the HealthyLife project.</p><p><ul><li>responsive, parallax</li><li>contact form</li></ul></p>",
    technologies: ["React", "Bootstrap", "PHP"],
  },
  {
    id: 21,
    title: "Universumhus",
    projectUrl: "universumhus",
    bgImg: "universumhus.jpg",
    desc: "<p>Website with administration panel</p>",
    technologies: ["HTML", "CSS", "JavaScript", "PHP"],
  },

  {
    id: 5,
    title: "Randi8",
    projectUrl: "randi8",
    bgImg: "randi8.jpg",
    desc: "<p>Dating Website with online payment option</p>",
    technologies: ["HTML", "CSS", "JavaScript/jQuery", "PHP", "MySQL"],
  },
  {
    id: 7,
    title: "Kuckófalva",
    projectUrl: "kuckofalva",
    bgImg: "kuckofalva.jpg",
    desc: "<p>Website with user-friendly admin panel.</p><p><ul><li>responsive</li><li>slideshow</li><li>garden playhouse design option</li><li>gallery - image viewer</li><li>contact form</li></ul></p>",
    technologies: ["HTML", "CSS", "JavaScript", "PHP"],
  },
  {
    id: 8,
    title: "eskuvod.net",
    projectUrl: "eskuvodnet",
    bgImg: "eskuvod.net.jpg",
    desc: "<p><ul><li>responsive</li><li>gallery with image viewer</li><li>contact form</li></ul></p>",
    technologies: ["HTML", "CSS", "JavaScript", "PHP"],
  },
  {
    id: 9,
    title: "hungarofolia",
    projectUrl: "hungarofolia",
    bgImg: "hungarofolia.jpg",
    desc: "<p><ul><li>slideshow</li><li>contact form</li></ul></p>",
    technologies: ["HTML", "CSS", "JavaScript", "PHP"],
  },
  {
    id: 10,
    title: "lavero",
    projectUrl: "lavero",
    bgImg: "lavero.jpg",
    desc: "<p>Website with user-friendly admin panel</p><p><ul><li>bilingual</li><li>responsive</li><li>slideshow</li></ul></p>",
    technologies: ["HTML", "CSS", "JavaScript", "PHP"],
  },
  {
    id: 11,
    title: "ml-auto",
    projectUrl: "ml-auto",
    bgImg: "ml-auto.jpg",
    desc: "<p>Website with 7 pages</p>",
    technologies: ["HTML", "CSS", "PHP"],
  },
  {
    id: 12,
    title: "drdonajo",
    projectUrl: "drdonajo",
    bgImg: "drdonajo.jpg",
    desc: "Website with user-friendly admin panel",
    technologies: ["HTML", "CSS", "JavaScript", "PHP"],
  },
  {
    id: 13,
    title: "MobilBoltkereső",
    projectUrl: "mobilboltkereso",
    bgImg: "mobilboltkereso.jpg",
    desc: "<p>Website with 7 pages.</p><p><ul><li>responsive</li><li>contact form</li></ul></p>",
    technologies: ["HTML", "CSS", "PHP"],
  },
  {
    id: 14,
    title: "Ruhavarázs",
    projectUrl: "ruhavarazs",
    bgImg: "ruhavarazs.jpg",
    desc: "<p>Simple website with 4 pages</p><p>Contact with send mail option</p><p>It's from a time when we haven't have to pay attention to building responsive websites.</p>",
    technologies: ["HTML", "CSS", "PHP"],
  },
  {
    id: 15,
    title: "HANG.FÉNY.DJ",
    projectUrl: "hangfenydj",
    bgImg: "hangfenydj.jpg",
    desc: "<ul><li>Website with 5 pages</li><li>There is an animated slideshow on the main page.</li><li>Gallery with image viewer</li><li>The website is not responsive (this is an early project, we haven't had to pay attention to making responsive websites yet)</li></ul>",
    technologies: ["HTML", "CSS", "JavaScript / jQuery", "PHP"],
  },
  {
    id: 16,
    title: "szocszolg22",
    projectUrl: "szocszolg22",
    bgImg: "szocszolg22.jpg",
    desc: "<p>Website with admin panel. Caritative project (the website provides social services)</p><p><ul><li>barrier-free website</li><li>contact form, maps</li></ul></p>",
    technologies: ["HTML", "CSS", "JavaScript", "PHP", "MySQL"],
  },
  {
    id: 17,
    title: "karpatiapanzio",
    projectUrl: "karpatiapanzio",
    bgImg: "karpatiapanzio.jpg",
    desc: "<p>Accommodation booking website with admin panel</p><p><ul><li>bilingual</li></ul></p>",
    technologies: ["HTML", "CSS", "JavaScript", "PHP", "MySQL"],
  },
  {
    id: 19,
    title: "mobilvalutavaltok",
    projectUrl: "mobilvalutavaltok",
    bgImg: "mobilvalutavaltok.jpg",
    desc: "<p>Website with 7 pages.</p><p><ul><li>responsive</li><li>contact form</li></ul></p>",
    technologies: ["HTML", "CSS", "PHP"],
  },
  {
    id: 20,
    title: "my69 webshop",
    projectUrl: "my69",
    bgImg: "my69-blured.jpg",
    desc: "<p>Bilingual Webshop with some other features, online payment option and customized admin panel.</p><br /><p><ul><li>responsive</li><li>forum</li><li>blog with comment option</li><li>ask from our expert</li><li>cart</li><li>wishlist</li><li>contact form</li><li>online payment</li></ul></p>",
    technologies: ["HTML", "CSS", "Bootstrap", "JavaScript", "PHP", "MySQL"],
  },
  {
    id: 21,
    title: "varroda22",
    projectUrl: "varroda22",
    bgImg: "varroda22.jpg",
    desc: "<p>Simple website for sewing</p><br /><p><ul><li>responsive</li></ul></p>",
    technologies: ["HTML", "CSS", "Bootstrap", "JavaScript"],
  },
];

export async function getProjectData(url) {
  return projectList.filter((project) => project.projectUrl === url);
}
